### ISSUE TITLE
Если опустить параметр -s, то происходит падение

### ISSUE THREAD

**Issue by zerobig** [alkoleft/bsldoc#5]
```bash
D:\Temp\RequestSchema.tmp>java -jar ./bsldoc-0.1.0.jar ./../RequestSchema/src/cfe ./api -f Docusaurus
java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "this.onlySubsystems" is null
        at ru.alkoleft.bsl.doc.commands.RenderCommand.run(RenderCommand.java:41)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.executeHelpRequest(CommandLine.java:2012)
        at picocli.CommandLine.executeHelpRequest(CommandLine.java:1983)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2268)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at ru.alkoleft.bsl.doc.Main.main(Main.java:9)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
```

**Comment by alkoleft** [comment]
Спасибо за интерес и тестирование. В скором времени не смогу поправить ошибки. Также вам пока не советую это делать, есть неслитая ветка с большим количеством изменений.
